### ISSUE TITLE
API网关：如何从  chart 0.4.x 迁移到 1.12.x

### ISSUE THREAD

**Issue by alex-smile** [TencentBlueKing/blueking-apigateway#189]
## 0. 预准备：values.yaml

1.10.x 新版本增加了 ETCD 依赖，请提前准备。

更新 values：
- [必须] 将 etcd 信息配置到 externalEtcd 中；
- [必须] 配置 defaultMicroGatewayInstanceId：一个 uuid 字符串，创建后不能修改
- [推荐] 在 bkrepo 中创建名为 `bk_apigateway` 的项目和用户，将用户名密码更新到 `bkrepoConfig`，不配置将影响网关 SDK 功能；
- [推荐] 增加一个日志采集的 DataId，用于存储网关内部模块日志，配置到 `apigateway.bkLogConfig.fileDataId`，不配置会复用标准输出的 DataId；
- [推荐] 梳理访问链路的中间代理地址，将地址列表整理到 `apigateway.pluginMetadata["bk-real-ip"].trustedAddresses` 中，如不配置，将会影响 IP 访问控制插件和客户端 IP 获取的逻辑；
- [推荐] 添加 operator 模块个性化配置
- [推荐] 删除 apiSupport 配置，已合并到 dashboard 模块
- [推荐] 删除 caddy 配置，已合并到 bk-esb 模块

### 1.1 备份数据库
因灰度会变更 database，所以灰度前，需要备份数据库：bk_esb，bk_apigateway，以便于出现问题时进行回滚。
- 准备恢复数据的指令，恢复数据后，重启 Release bk-apigateway 的 Pod 即可

### 1.1 准备 values-canary.yaml

准备 values-canary.yaml，示例如下：
```yaml
registerCrds: false

apigateway:
  bkapiServiceName: ""
  # 初始时，不创建新 Pod
  replicaCount: 0
  ingress:
    annotations:
      # 标记此 Ingress 为金丝雀发布
      nginx.ingress.kubernetes.io/canary: "true"
      # API 服务，设置灰度比例，范围：0 ~ 100。初始时，不灰度流量
      nginx.ingress.kubernetes.io/canary-weight: "0"

dashboard:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/canary: "true"
      # 前端项目，用户手动设置浏览器 Cookies：canary=always，则灰度此用户的请求
      nginx.ingress.kubernetes.io/canary-by-cookie: "canary"
      # 设置权重比例为 100，不灰度前端项目，直接发布
      # nginx.ingress.kubernetes.io/canary-weight: "100"

dashboardFe:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/canary: "true"
      # 前端项目，用户手动设置浏览器 Cookies：canary=always，则灰度此用户的请求
      nginx.ingress.kubernetes.io/canary-by-cookie: "canary"
      # 设置权重比例为 100，不灰度前端项目，直接发布
      # nginx.ingress.kubernetes.io/canary-weight: "100"
```

### 1.2 发布金丝雀 Release

```bash
# values.yaml 为正常发布的配置，values-canary.yaml 为金丝雀发布的特殊配置
helm install bk-apigateway-canary bkee/bk-apigateway -f values.yaml -f values-canary.yaml -n blueking
```

### 1.3 检查 bk-esb 组件数据，并将其同步到 apigateway

新版中，用户访问组件 API，请求流程如下：user -> apigateway -> bk-esb -> backend service。
因此，需要将 bk-esb 组件数据同步至 apigateway；为方便二者数据的映射，bk-esb 中的部分组件需要拆分或调整。
```bash
# 进入 dashboard 容器
kubectl exec -it bk-apigateway-canary-dashboard-<xxx> -- bash -n blueking

# 拆分组件：检查组件中同一 path 是否存在 method=""，及其它方法的组件，此类组件需要拆分或调整
# 执行过程中：部分组件直接修改，部分组件会要求确认；如无输出表示无需处理
python manage.py split_component_method [--dry-run]
- --dry-run: 不实际修改数据，可用于测试

# 同步 bk-esb 组件到 apigateway；此指令耗时 2 ~ 5 分钟，请等待
python manage.py sync_to_gateway_and_release

# 同步组件权限数据到 apigateway
python manage.py sync_esb_permissions_to_gateway
```

验证 bk-esb 组件。登录网关管理端 http://apigw.\_\_bk_domain\_\_，进入网关 bk-esb 管理页
 - `基本设置 => 资源管理`，检查网关 bk-esb 中资源是否为空
 - `权限管理 => 应用权限`，检查网关 bk-esb 权限数据是否正确

### 1.4 同步 dashboard 数据到 etcd

dashboard 创建成功后，进入 dashboard 同步网关数据到 etcd。
- 0.4.x 为 Go 版本网关，不依赖 etcd；1.10.x 为 apisix 网关，依赖 etcd。切换时，需提前为 1.10.x apisix 网关准备 etcd 数据。
```bash
# 进入 dashboard 容器
kubectl exec -it bk-apigateway-canary-dashboard-<xxx> -- bash -n blueking

# 执行 django command，将网关数据同步到 etcd
python manage.py sync_releases_to_shared_micro_gateway_parallel
```

### 1.4 灰度发布

- 初始时，金丝雀 deploy bk-apigateway-canary-apigateway 未创建 Pod
- 手动将金丝雀 deploy bk-apigateway-canary-apigateway 的 spec.replicas 改为 1，创建 1 个 Pod
- 手动将金丝雀 ingress bk-apigateway-canary-apigateway metadata.annotations."nginx.ingress.kubernetes.io/canary-weight" 改为 10，灰度 10% 的流量。请通过请求流水观察 API 网关服务是否正常
- 手动将金丝雀 deploy bk-apigateway-canary-apigateway 的 spec.replicas 改为 3，创建 3 个 Pod
- 手动将金丝雀 ingress bk-apigateway-canary-apigateway metadata.annotations."nginx.ingress.kubernetes.io/canary-weight" 改为 20，灰度 20% 的流量
- [可选] 浏览器中打开网关管理端，手动在 Cookies  中设置 canary=always，测试管理端功能
- 按正常流程发布原 Release bk-apigateway。待原 Release 更新成功后，调整 ingress bk-apigateway-canary-apigateway，将 canary-weight 调整为 0
- 检查 bk-apigateway-canary-bk-esb-\<xxx\>、bk-apigateway-canary-apigateway-\<xxx\> 中是否仍有流量
- 如上一步检查，bk-apigateway-canary 中 apigateway、bk-esb 无业务流量，则可以删除金丝雀 Release，灰度结束

参考指令：
```bash
# 编辑 deploy
kubectl edit deploy bk-apigateway-canary-apigateway -n blueking

# 编辑 ingress
kubectl edit ingress bk-apigateway-canary-apigateway -n blueking

# 检查 bk-esb pod 是否有流量
kubectl logs bk-apigateway-canary-bk-esb-<xxx> --tail 20 -f -n blueking
# 检查 apigateway 是否有流量
kubectl exec -it bk-apigateway-canary-apigateway-<xxx> -- bash -n blueking
tail -f /usr/local/apisix/logs/access.log

# 删除金丝雀 Release
helm uninstall bk-apigateway-canary -n blueking
```
